nombre: node-exporter
descripcion: Exportador de métricas del sistema para Prometheus.
puerto_por_defecto: 9100
icono: https://prometheus.io/assets/favicons/android-chrome-192x192.png
volumenes: []
dependencias: []
