users:
  admin:
    displayname: "Administrador"
    password: "$argon2id$v=19$m=65536,t=3,p=4$X8XIn9HIs7B9PloMvWd2vw$I6X9v6fN/fJj7z4G5LwX8A7yQyS7H9f0uG5G5G5G5G5" # Password: admin
    email: admin@osanchez.org
    groups:
      - admins
      - users
